# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Thu Jun 23 17:23:57 2022
#

import wx
import sys
if sys.version_info[0] == 2:
    import ConfigParser as configparser
else:
    import configparser
from ReaCommon import NetworkHelper, DAEMON_CONFS, get_cwd

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

class RccuFrame(wx.Frame):


	def __init__(self, *args, **kwds):
		# begin wxGlade: RccuFrame.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE | wx.FULL_REPAINT_ON_RESIZE
		wx.Frame.__init__(self, *args, **kwds)
		self.rccu_statusbar = self.CreateStatusBar(1)
		
		# Tool Bar
		self.rccu_toolbar = wx.ToolBar(self, -1, style=wx.TB_DEFAULT_STYLE | wx.TB_HORZ_LAYOUT)
		self.SetToolBar(self.rccu_toolbar)
		self.rccu_toolbar.AddTool(0, "&New", wx.Bitmap("dist/wxGlade/material/new.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Apply Defaults", "")
		self.rccu_toolbar.AddTool(1, "&Open", wx.Bitmap("dist/wxGlade/material/open.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Open Config", "")
		self.rccu_toolbar.AddTool(2, "&Save", wx.Bitmap("dist/wxGlade/material/save.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Save Config", "")
		self.rccu_toolbar.AddSeparator()
		self.rccu_toolbar.AddTool(3, "&About", wx.Bitmap("dist/wxGlade/material/info.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "About Us", "")
		self.rccu_toolbar.AddTool(4, "&Exit", wx.Bitmap("dist/wxGlade/material/exit.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Exit", "")
		# Tool Bar end
		self.tabs = wx.Notebook(self, wx.ID_ANY)
		self.tabDaemon = wx.Panel(self.tabs, wx.ID_ANY)
		self.cbbDeviceName = wx.ComboBox(self.tabDaemon, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
		self.btnDevNameDefault = wx.Button(self.tabDaemon, wx.ID_ANY, "Default")
		self.cbbListen = wx.ComboBox(self.tabDaemon, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
		self.fldListenPort = wx.TextCtrl(self.tabDaemon, wx.ID_ANY, "")
		self.btnListenDefault = wx.Button(self.tabDaemon, wx.ID_ANY, "Default")
		self.fldConnectIP = wx.TextCtrl(self.tabDaemon, wx.ID_ANY, "")
		self.fldConnectPort = wx.TextCtrl(self.tabDaemon, wx.ID_ANY, "")
		self.btnConnectDefault = wx.Button(self.tabDaemon, wx.ID_ANY, "Default")
		self.chkDebugSwitch = wx.CheckBox(self.tabDaemon, wx.ID_ANY, "", style=wx.CHK_2STATE)
		self.choiceLoglevel = wx.Choice(self.tabDaemon, wx.ID_ANY, choices=["ERROR", "WARN", "INFO", "DEBUG", "TRACE"])
		self.tabPaths = wx.Panel(self.tabs, wx.ID_ANY)
		self.fldLoggingPath = wx.TextCtrl(self.tabPaths, wx.ID_ANY, "")
		self.fldReaControlPath = wx.TextCtrl(self.tabPaths, wx.ID_ANY, "")
		self.fldGitPath = wx.TextCtrl(self.tabPaths, wx.ID_ANY, "")
		self.fldReaperOSCPath = wx.TextCtrl(self.tabPaths, wx.ID_ANY, "")
		self.tabDevices = wx.Panel(self.tabs, wx.ID_ANY)
		self.listDevices = wx.ListCtrl(self.tabDevices, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_TOOL, self.on_fileNew, id=0)
		self.Bind(wx.EVT_TOOL, self.on_fileOpen, id=1)
		self.Bind(wx.EVT_TOOL, self.on_fileSave, id=2)
		self.Bind(wx.EVT_TOOL, self.on_about, id=3)
		self.Bind(wx.EVT_TOOL, self.on_exit, id=4)
		self.Bind(wx.EVT_BUTTON, self.btnDevNameDefault_onclick, self.btnDevNameDefault)
		self.Bind(wx.EVT_BUTTON, self.btnListenDefault_onclick, self.btnListenDefault)
		self.Bind(wx.EVT_BUTTON, self.btnConnectDefault_onclick, self.btnConnectDefault)
		# end wxGlade

		self.rccu_init()

	def text_return(self, event):
		self.st.Clear()
		self.st.Append('3')
		self.st.Append('4')

	def __set_properties(self):
		# begin wxGlade: RccuFrame.__set_properties
		self.SetTitle("ReaControl Configuration Utility")
		_icon = wx.NullIcon
		_icon.CopyFromBitmap(wx.Bitmap("dist/wxGlade/wt_icon_shapes/hammer.png", wx.BITMAP_TYPE_ANY))
		self.SetIcon(_icon)
		self.SetFocus()
		self.rccu_statusbar.SetStatusWidths([-1])
		
		# statusbar fields
		rccu_statusbar_fields = ["ReaControl is open source - please help improve me at https://github.com/phunkyg/ReaControl24"]
		for i in range(len(rccu_statusbar_fields)):
			self.rccu_statusbar.SetStatusText(rccu_statusbar_fields[i], i)
		self.rccu_toolbar.SetToolBitmapSize((32, 32))
		self.rccu_toolbar.SetMargins((2, 8))
		self.rccu_toolbar.Realize()
		self.cbbDeviceName.SetMinSize((160, 23))
		self.cbbListen.SetMinSize((160, 23))
		self.fldListenPort.SetMinSize((52, 22))
		self.fldConnectIP.SetMinSize((160, 22))
		self.fldConnectPort.SetMinSize((52, 22))
		self.choiceLoglevel.SetSelection(0)
		self.fldLoggingPath.SetMinSize((300, 22))
		self.fldReaControlPath.SetMinSize((300, 22))
		self.fldGitPath.SetMinSize((300, 22))
		self.fldReaperOSCPath.SetMinSize((300, 22))
		self.listDevices.AppendColumn("Name", format=wx.LIST_FORMAT_LEFT, width=-1)
		self.listDevices.AppendColumn("device", format=wx.LIST_FORMAT_LEFT, width=-1)
		self.listDevices.AppendColumn("version", format=wx.LIST_FORMAT_LEFT, width=-1)
		self.tabDevices.Enable(False)
		self.tabDevices.Hide()
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: RccuFrame.__do_layout
		rccu_display = wx.BoxSizer(wx.VERTICAL)
		sizer_1 = wx.BoxSizer(wx.VERTICAL)
		sizer_3 = wx.BoxSizer(wx.VERTICAL)
		sizer_15 = wx.BoxSizer(wx.VERTICAL)
		sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_20 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_2 = wx.BoxSizer(wx.VERTICAL)
		sizer_23 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_22 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
		lblDevName = wx.StaticText(self.tabDaemon, wx.ID_ANY, "Set Network Interface", style=wx.ALIGN_RIGHT)
		lblDevName.SetMinSize((160, 16))
		lblDevName.SetToolTip("Ethernet interface to the same network as the Desk.")
		sizer_4.Add(lblDevName, 0, wx.ALL, 8)
		sizer_4.Add(self.cbbDeviceName, 0, wx.ALL, 8)
		sizer_4.Add(self.btnDevNameDefault, 0, wx.ALL, 8)
		sizer_2.Add(sizer_4, 0, wx.ALL, 0)
		static_line_1 = wx.StaticLine(self.tabDaemon, wx.ID_ANY)
		sizer_2.Add(static_line_1, 0, wx.ALL | wx.EXPAND, 8)
		stxClientParams = wx.StaticText(self.tabDaemon, wx.ID_ANY, "Settings to pass to Reaper OSC")
		sizer_2.Add(stxClientParams, 0, wx.ALL, 8)
		lblListen = wx.StaticText(self.tabDaemon, wx.ID_ANY, "OSC Listen Address", style=wx.ALIGN_RIGHT)
		lblListen.SetMinSize((160, 22))
		lblListen.SetToolTip("Ethernet interface to the same network as the Desk.")
		sizer_7.Add(lblListen, 0, wx.ALL, 8)
		sizer_7.Add(self.cbbListen, 0, wx.BOTTOM | wx.LEFT | wx.TOP, 8)
		lbl_psep_ola = wx.StaticText(self.tabDaemon, wx.ID_ANY, ":")
		sizer_7.Add(lbl_psep_ola, 0, wx.TOP, 11)
		sizer_7.Add(self.fldListenPort, 0, wx.BOTTOM | wx.RIGHT | wx.TOP, 8)
		sizer_7.Add(self.btnListenDefault, 0, wx.ALL, 8)
		sizer_2.Add(sizer_7, 0, wx.ALL, 0)
		lblConnect = wx.StaticText(self.tabDaemon, wx.ID_ANY, "OSC Connect Address", style=wx.ALIGN_RIGHT)
		lblConnect.SetMinSize((160, 22))
		lblConnect.SetToolTip("Ethernet interface to the same network as the Desk.")
		sizer_9.Add(lblConnect, 0, wx.ALL, 8)
		sizer_9.Add(self.fldConnectIP, 0, wx.BOTTOM | wx.LEFT | wx.TOP, 8)
		lbl_psep_oca = wx.StaticText(self.tabDaemon, wx.ID_ANY, ":")
		sizer_9.Add(lbl_psep_oca, 0, wx.TOP, 11)
		sizer_9.Add(self.fldConnectPort, 0, wx.BOTTOM | wx.RIGHT | wx.TOP, 8)
		sizer_9.Add(self.btnConnectDefault, 0, wx.ALL, 8)
		sizer_2.Add(sizer_9, 0, wx.ALL, 0)
		static_line_2 = wx.StaticLine(self.tabDaemon, wx.ID_ANY)
		sizer_2.Add(static_line_2, 0, wx.ALL | wx.EXPAND, 8)
		lblDebugSwitch = wx.StaticText(self.tabDaemon, wx.ID_ANY, "Debug Mode", style=wx.ALIGN_RIGHT)
		lblDebugSwitch.SetMinSize((160, 22))
		sizer_22.Add(lblDebugSwitch, 0, wx.ALL, 8)
		sizer_22.Add(self.chkDebugSwitch, 0, wx.ALL, 8)
		sizer_2.Add(sizer_22, 0, 0, 0)
		lblLogLevel = wx.StaticText(self.tabDaemon, wx.ID_ANY, "Logging Level", style=wx.ALIGN_RIGHT)
		lblLogLevel.SetMinSize((160, 22))
		sizer_23.Add(lblLogLevel, 0, wx.ALL, 8)
		sizer_23.Add(self.choiceLoglevel, 0, wx.ALL, 8)
		sizer_2.Add(sizer_23, 0, 0, 0)
		self.tabDaemon.SetSizer(sizer_2)
		lblTabTitles = wx.StaticText(self.tabPaths, wx.ID_ANY, "Please enter the paths for ReaControl on this host.")
		lblTabTitles.SetMinSize((320, 24))
		sizer_15.Add(lblTabTitles, 0, wx.ALL, 8)
		hzLine = wx.StaticLine(self.tabPaths, wx.ID_ANY)
		sizer_15.Add(hzLine, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 8)
		lblLoggingPath = wx.StaticText(self.tabPaths, wx.ID_ANY, "Logging Path", style=wx.ALIGN_RIGHT)
		lblLoggingPath.SetMinSize((160, 16))
		lblLoggingPath.SetToolTip("Insert path where you want to save logs")
		sizer_20.Add(lblLoggingPath, 0, wx.ALL, 8)
		sizer_20.Add(self.fldLoggingPath, 0, wx.ALL, 8)
		sizer_15.Add(sizer_20, 1, wx.ALL | wx.EXPAND, 0)
		lblReaControlPath = wx.StaticText(self.tabPaths, wx.ID_ANY, "ReaControl Path", style=wx.ALIGN_RIGHT)
		lblReaControlPath.SetMinSize((160, 16))
		sizer_16.Add(lblReaControlPath, 0, wx.ALL, 8)
		sizer_16.Add(self.fldReaControlPath, 0, wx.ALL, 8)
		sizer_15.Add(sizer_16, 1, wx.ALL | wx.EXPAND, 0)
		lblGitPath = wx.StaticText(self.tabPaths, wx.ID_ANY, "Git repository URL", style=wx.ALIGN_RIGHT)
		lblGitPath.SetMinSize((160, 16))
		sizer_18.Add(lblGitPath, 0, wx.ALL, 8)
		sizer_18.Add(self.fldGitPath, 0, wx.ALL, 8)
		sizer_15.Add(sizer_18, 1, wx.EXPAND, 0)
		lblReaperOSCPath = wx.StaticText(self.tabPaths, wx.ID_ANY, "Reaper OSC Path", style=wx.ALIGN_RIGHT)
		lblReaperOSCPath.SetMinSize((160, 16))
		sizer_19.Add(lblReaperOSCPath, 0, wx.ALL, 8)
		sizer_19.Add(self.fldReaperOSCPath, 0, wx.ALL, 8)
		sizer_15.Add(sizer_19, 1, wx.EXPAND, 0)
		self.tabPaths.SetSizer(sizer_15)
		sizer_3.Add(self.listDevices, 1, wx.EXPAND, 0)
		self.tabDevices.SetSizer(sizer_3)
		self.tabs.AddPage(self.tabDaemon, "daemon")
		self.tabs.AddPage(self.tabPaths, "paths")
		self.tabs.AddPage(self.tabDevices, "devices")
		sizer_1.Add(self.tabs, 1, wx.ALL | wx.EXPAND, 16)
		rccu_display.Add(sizer_1, 0, wx.EXPAND, 0)
		self.SetSizer(rccu_display)
		rccu_display.Fit(self)
		rccu_display.SetSizeHints(self)
		self.Layout()
		self.Centre()
		# end wxGlade

	def empty_config(self):
		config = configparser.ConfigParser()

		config.add_section('daemon')
		config.add_section('paths')
		config.add_section('logging')

		config.set('daemon','network', 		u'')
		config.set('daemon','listen',		u'')
		config.set('daemon','listen_port',	u'')
		config.set('daemon','connect',		u'')
		config.set('daemon','connect_port', u'')
		config.set('daemon','debug',		u'')
		config.set('paths','logdir',		u'')
		config.set('paths','gitrepo_url',	u'')
		config.set('paths','reaperosc_dir', u'')
		config.set('logging','loglevel',    u'')
		return config


	def on_fileOpen(self, event): # wxGlade: RccuFrame.<event_handler>
		self.read_daemon_files()
		event.Skip()

	def read_daemon_files(self, defaultonly=1):
		config = self.empty_config()

		self.rccu_statusbar.SetStatusText("Reading daemon configs...")
		config.read(DAEMON_CONFS[0:defaultonly+1])

		# parse config object resulting from all file reads
		network = config.get('daemon', 'network')
		if network:
			self.cbbDeviceName.SetValue(network)
		listen = config.get('daemon', 'listen')
		if listen:
			self.cbbListen.SetValue(listen)
		listen_port = RccuFrame.mk_int(config.get('daemon', 'listen_port'))
		if listen_port:
			self.fldListenPort.SetValue(str(listen_port)) # TODO wxWidgets numerical
		connect = config.get('daemon', 'connect')
		if connect:
			self.fldConnectIP.SetValue(connect)
		connect_port = RccuFrame.mk_int(config.get('daemon', 'connect_port'))
		if connect_port:
			self.fldConnectPort.SetValue(str(connect_port))    # TODO wxWidgets numerical
		debug = ('True' == config.get('daemon', 'debug'))
		currdebug = self.chkDebugSwitch.GetValue()
		if debug != currdebug:
			self.chkDebugSwitch.SetValue(debug)
		gitrepo_url = config.get('paths',  'gitrepo_url')
		if gitrepo_url:
			self.fldGitPath.SetValue(gitrepo_url)
		logdir = config.get('paths',  'logdir')
		if logdir:
			self.fldLoggingPath.SetValue(logdir)
		reaperosc_dir = config.get('paths', 'reaperosc_dir')
		if reaperosc_dir:
			self.fldReaperOSCPath.SetValue(reaperosc_dir)
		loglevel = config.get('logging','loglevel')
		if loglevel:
			self.choiceLoglevel.SetStringSelection(loglevel)
		reacontrol_dir = get_cwd()
		if reacontrol_dir:
			self.fldReaControlPath.SetValue(reacontrol_dir)

		self.rccu_statusbar.SetStatusText("Config File(s) Open OK.")

	@staticmethod
	def mk_int(s):
		s = s or ''
		s = s.strip()
		return int(s) if s else None

	def on_fileSave(self, event):  # wxGlade: RccuFrame.<event_handler>
		# assert mandatory fields

		config = self.empty_config()

		network = self.cbbDeviceName.GetValue()
		listen = self.cbbListen.GetValue()
		listen_port = self.fldListenPort.GetValue()
		connect = self.fldConnectIP.GetValue()
		connect_port = self.fldConnectPort.GetValue()

		if any([
			u'' == network,
			u'' == listen,
			u'' == listen_port,
			u'' == connect,
			u'' == connect_port
		]):
			self.rccu_statusbar.SetStatusText(
				"Can't save file without all mandatory fields: network, listen, listen_port, connect, connect_port"
			)
			event.Skip()
			return

		if network != u'':
			config.set('daemon','network',network)
		if listen != u'':
			config.set('daemon','listen',listen)
		if listen_port != u'':
			config.set('daemon','listen_port',listen_port)
		if connect != u'':
			config.set('daemon','connect',connect)
		if connect_port != u'':
			config.set('daemon','connect_port', connect_port)

		debug = self.chkDebugSwitch.GetValue()
		config.set('daemon','debug',debug)
		logdir = self.fldLoggingPath.GetValue()
		if logdir != u'':
			config.set('paths','logdir',logdir)
		gitrepo_url = self.fldGitPath.GetValue()
		if gitrepo_url != u'':
			config.set('paths','gitrepo_url', gitrepo_url)
		reaperosc_dir = self.fldReaperOSCPath.GetValue()
		if reaperosc_dir != u'':
			config.set('paths','reaperosc_dir', reaperosc_dir)
		loglevel = self.choiceLoglevel.GetStringSelection()
		if loglevel != u'':
			config.set('logging','loglevel', loglevel)
		reacontrol_dir = self.fldReaControlPath.GetValue()
		if reacontrol_dir != u'':
			config.set('paths','reacontrol_dir', reacontrol_dir)


		with open(DAEMON_CONFS[1], 'w') as f:
			config.write(f)

		# old parser delete if done with
		# network = ''
		# with open(RccuFrame.default_daemon_conf, 'r') as f:
		# 	for line in f:
		# 		self.rccu_statusbar.SetStatusText(line)
		# 		if line.startswith('network = '):
		# 			network = line[11:-2]
		# self.rccu_statusbar.SetStatusText(network)
		#
		# self.cbbDeviceName.SetValue(network)

		self.rccu_statusbar.SetStatusText("Config File(s) Saved OK.")
		event.Skip()

	def on_about(self, event):  # wxGlade: RccuFrame.<event_handler>
		print("Event handler 'on_about' not implemented!")
		event.Skip()

	def on_exit(self, event):  # wxGlade: RccuFrame.<event_handler>
		wx.CallAfter(self.Destroy)

	def cbbDeviceName_onComboBox(self, event):  # wxGlade: RccuFrame.<event_handler>
		print("Event handler 'cbbDeviceName_onComboBox' not implemented!")
		event.Skip()
	def btnDevNameDefault_onclick(self, event):  # wxGlade: RccuFrame.<event_handler>
		self.btnDevName_default()
		event.Skip()
	def btnDevName_default(self):
		if self.default_network:
			self.cbbDeviceName.SetValue(self.default_network[0])
		else:
			self.rccu_statusbar.SetStatusText('No Default Network found! Please select manually using the drop down list.')


	def rccu_init(self):
		self.networkhelper = NetworkHelper()
		# clear and populate devices list from network helper
		self.networks = self.networkhelper.list_networks()
		self.default_network = next((obj for obj in self.networks.iteritems() if obj[1].get('default')))
		self.cbbDeviceName.Clear()
		self.cbbListen.Clear()
		for key, obj in self.networks.iteritems():
			self.cbbDeviceName.Append(key)
			ip = obj.get('ip')
			if ip:
				addr = ip[0].get('addr')
				self.cbbListen.Append(self.cbbListen_formatentry(addr, key))

	def btnListenDefault_onclick(self, event):  # wxGlade: RccuFrame.<event_handler>
		self.btnListen_default()
		event.Skip()

	def btnListen_default(self):
		if self.default_network:
			ip = self.default_network[1].get('ip')[0].get('addr')
			self.cbbListen.SetValue(self.cbbListen_formatentry(ip, self.default_network[0]))
			self.fldListenPort.SetValue(str(9124))
		else:
			self.rccu_statusbar.SetStatusText('No Default Network found! Please select manually using the drop down list.')

	def cbbListen_formatentry(self, addr, iface):
		return '{} ({})'.format(addr, iface)

	def btnConnectDefault_onclick(self, event):  # wxGlade: RccuFrame.<event_handler>
		self.btnConnect_default()
		event.Skip()

	def btnConnect_default(self):
		if self.default_network:
			ip = self.default_network[1].get('ip')[0].get('addr')
			self.fldConnectIP.SetValue(ip)
			self.fldConnectPort.SetValue(str(9125))
		else:
			self.rccu_statusbar.SetStatusText('No Default Network found! Please enter manually.')

	def on_fileNew(self, event):  # wxGlade: RccuFrame.<event_handler>
		self.read_daemon_files(0)
		self.btnDevName_default()
		self.btnListen_default()
		self.btnConnect_default()

		self.rccu_statusbar.SetStatusText("All Defaults Applied!")
		event.Skip()


# end of class RccuFrame
