#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Sun Jun 26 21:22:42 2022
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from RccuFrame import RccuFrame


class rccu(wx.App):
	def OnInit(self):
		self.rccu = RccuFrame(None, wx.ID_ANY, "")
		self.SetTopWindow(self.rccu)
		self.rccu.Show()
		return True

# end of class rccu

if __name__ == "__main__":
	ReaControl_ConfigUtil = rccu(0)
	ReaControl_ConfigUtil.MainLoop()
