#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Sun Jun 26 22:59:19 2022
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class frm_launcher(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frm_launcher.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((363, 22))
        
        # Tool Bar
        self.frame_toolbar = wx.ToolBar(self, -1, style=wx.TB_DEFAULT_STYLE)
        self.SetToolBar(self.frame_toolbar)
        self.frame_toolbar.AddTool(wx.ID_ANY, "Run", wx.Bitmap("/Users/scottmckinnon/Downloads/play_arrow_FILL0_wght300_GRAD200_opsz48.png", wx.BITMAP_TYPE_ANY), wx.Bitmap("/Users/scottmckinnon/Downloads/not_started_FILL0_wght300_GRAD200_opsz48.png", wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "Run ReaControl24", "")
        self.frame_toolbar.AddTool(wx.ID_ANY, "Stop", wx.Bitmap("/Users/scottmckinnon/Downloads/stop_circle_FILL0_wght300_GRAD200_opsz48.png", wx.BITMAP_TYPE_ANY), wx.Bitmap("/Users/scottmckinnon/Downloads/stop_circle_FILL0_wght300_GRAD200_opsz48.png", wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "Stop ReaControl24", "")
        self.frame_toolbar.AddTool(wx.ID_ANY, "Config", wx.Bitmap("/Users/scottmckinnon/Downloads/settings_FILL0_wght300_GRAD200_opsz48.png", wx.BITMAP_TYPE_ANY), wx.Bitmap("/Users/scottmckinnon/Downloads/settings_FILL0_wght300_GRAD200_opsz48.png", wx.BITMAP_TYPE_ANY), wx.ITEM_NORMAL, "Configure ReaControl24", "")
        # Tool Bar end

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frm_launcher.__set_properties
        self.SetTitle("ReaControl Launcher")
        self.frame_toolbar.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frm_launcher.__do_layout
        self.Layout()
        # end wxGlade

# end of class frm_launcher

class MyApp(wx.App):
    def OnInit(self):
        self.reaControl_launcher = frm_launcher(None, wx.ID_ANY, "")
        self.SetTopWindow(self.reaControl_launcher)
        self.reaControl_launcher.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
