[daemon]
# daemon launcher defaults
# network = en0   # can't really default this in a file but the gui and command line can
# listen = 127.0.0.1    # using loopback adapter is an untested config so there isn't a default
listen_port = 9124
# connect = 127.0.0.1   # using loopback adapter is an untested config so there isn't a default
connect_port = 9125
debug = False

[paths]
logdir = ./logs
# reacontrol_dir = ..     # really only for the gui, has to be determined at runtime. TODO.
gitrepo_url = https://github.com/phunkyg/ReaControl24/
reaperosc_dir = ~/Library/Application Support/REAPER/OSC

[logging]
loglevel = INFO
logformat = %(asctime)s\t%(name)s\t%(levelname)s\t%(threadName)s\t%(funcName)s\t%(lineno)d\t%(message)s

[config]
# How fast to restore prior scribble strip content after hot change
timing_scribble_restore = 1
# shared secret used for inter process comms (can be anything)
auth = be_in-control
