[daemon]
network = en9
listen = 172.16.7.4
listen_port = 9124
connect = 172.16.7.4
connect_port = 9125
debug = False

[paths]
logdir = ./logs
gitrepo_url = https://github.com/phunkyg/ReaControl24/
reaperosc_dir = ~/Library/Application Support/REAPER/OSC
reacontrol_dir = ~/PycharmProjects/ReaControl24

[logging]
loglevel = INFO

